# Generated by Django 5.0.4 on 2024-04-27 11:19

import appointments.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='availability',
            name='end_day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Friday', max_length=10),
        ),
        migrations.AddField(
            model_name='availability',
            name='start_day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(validators=[appointments.models.validate_evening_time]),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(validators=[appointments.models.validate_evening_time]),
        ),
    ]
